services:

  postgres_db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - percentage-net
    volumes:
      - postgres-data:/var/lib/postgresql/data

  percentage-calculation-api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE: percentage-calculation-api
    container_name: percentage-calculation-api
    ports:
      - "8082:8082"
    depends_on:
      - postgres_db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: true
    networks:
      - percentage-net

  percentage-provider-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE: percentage-provider-service
    container_name: percentage-provider-service
    ports:
      - "8081:8081"
    networks:
      - percentage-net
volumes:
  postgres-data:

networks:
  percentage-net:
    driver: bridge


