# Usamos la imagen oficial de OpenJDK
FROM openjdk:21-jdk-slim

# Establecemos el directorio de trabajo
WORKDIR /app

# Copiamos el jar de tu aplicación en el contenedor
COPY target/percentage-provider-service-*.jar /app/percentage-provider-service.jar

# Exponemos el puerto 8081 para el microservicio
EXPOSE 8081

# Comando para ejecutar la aplicación
CMD ["java", "-jar", "percentage-provider-service.jar"]
